# Diccionario generado automáticamente para features_valid
dict_features_valid = {'Monthly_Charges': 'float64',
                       'Total_Charges': 'float64',
                       'Senior_Citizen': 'float64',
                       'Year': 'float64',
                       'Month': 'float64',
                       'Day': 'float64',
                       'dow': 'float64',
                       'Type_one year': 'bool',
                       'Type_two year': 'bool',
                       'Paperless_Billing_yes': 'bool',
                       'Payment_Method_credit card': 'bool',
                       'Payment_Method_electronic check': 'bool',
                       'Payment_Method_mailed check': 'bool',
                       'Gender_male': 'bool',
                       'Partner_yes': 'bool',
                       'Dependents_yes': 'bool',
                       'Multiple_Lines_yes': 'bool',
                       'Internet_Service_fiber optic': 'bool',
                       'Internet_Service_no': 'bool',
                       'Online_Security_yes': 'bool',
                       'Online_Backup_yes': 'bool',
                       'Device_Protection_yes': 'bool',
                       'Tech_Support_yes': 'bool',
                       'Streaming_TV_yes': 'bool',
                       'Streaming_Movies_yes': 'bool'}
